name: stdc
description: A minimal-abstraction Standard C Library implementation for Dart. Designed for C programmers to seamlessly use familiar functions like stdc.printf or stdc.sin.
version: 0.1.0
repository: https://github.com/JedizLaPulga/stdc

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
